import { Router } from 'express';
import authRoutes from './auth.routes';
import profileRoutes from './profile.routes';
import usersRoutes from './users.routes';
import likeRoutes from './like.routes';
import chatRoutes from './chat.routes';
import walletRoutes from './wallet.routes';
import photosRoutes from './photos.routes';
import visitsRoutes from './visits.routes';
import notificationRoutes from './notification.routes';
import favoritesRoutes from './favorites.routes';
import blocksRoutes from './blocks.routes';
import settingsRoutes from './settings.routes';
import statusRoutes from './status.routes';
import adminRoutes from './admin.routes';
import reportsRoutes from './reports.routes';
import pushTokenRoutes from './pushtoken.routes';
import retentionRoutes from './retention.routes';
import flagsRoutes from './flags.routes';
import backupRoutes from './backup.routes';
import fraudRoutes from './fraud.routes';
import mediaRoutes from './media.routes';
import moderationRoutes from './moderation.routes';
import feedRoutes from './feed.routes';
import voiceRoutes from './voice.routes';
import callRoutes from './call.routes';
import paymentRoutes from './payment.routes';
import subscriptionRoutes from './subscription.routes';
import boostRoutes from './boost.routes';
import offerRoutes from './offer.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/profile', profileRoutes);
router.use('/users', usersRoutes);
router.use('/likes', likeRoutes);
router.use('/chat', chatRoutes);
router.use('/wallet', walletRoutes);
router.use('/photos', photosRoutes);
router.use('/visits',        visitsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/favorites',     favoritesRoutes);
router.use('/blocks',        blocksRoutes);
router.use('/settings',      settingsRoutes);
router.use('/status',        statusRoutes);
router.use('/admin',         adminRoutes);
router.use('/reports',       reportsRoutes);
router.use('/push-tokens',   pushTokenRoutes);
router.use('/retention',     retentionRoutes);
router.use('/flags',         flagsRoutes);
router.use('/backup',        backupRoutes);
router.use('/fraud',         fraudRoutes);
router.use('/media',         mediaRoutes);
router.use('/moderation',    moderationRoutes);
router.use('/feed',          feedRoutes);
router.use('/voice',         voiceRoutes);
router.use('/calls',         callRoutes);
router.use('/payments',      paymentRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/boosts',        boostRoutes);
router.use('/offers',        offerRoutes);

export default router;
